# Generated by Django 5.0.1 on 2024-02-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipes_count',
            field=models.IntegerField(default=0, verbose_name='Количество использования'),
        ),
    ]
