# Generated by Django 5.0.1 on 2024-02-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipeingredients',
            table='recipe_ingredient',
        ),
    ]
