# Generated by Django 5.0.1 on 2024-02-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_rename_product_recipeingredients_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='cookbook.RecipeIngredients', to='cookbook.product'),
        ),
    ]
