# Generated by Django 5.0.1 on 2024-02-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
